a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('É um número?', a.isnumeric()) 
print('É alfabético?', a.isalpha())
print('Está em maiúsculas?', a.isupper())
print('Está em minúsculas?', a.islower())
print('Está capitalizada?', a.istitle())
print('Caixa alta: ',a.upper())
